apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-capture-enrichment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-capture-enrichment-service
  template:
    metadata:
      labels:
        app: trade-capture-enrichment-service
    spec:
      containers:
        - name: trade-capture-enrichment-service
          image: docker.io/akshitasdock/trade-capture-enrichment-service:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: trade-capture-enrichment-service
spec:
  selector:
    app: trade-capture-enrichment-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP